disabled_rules:
  - identifier_name
  - trailing_whitespace
  - force_cast
opt_in_rules:
  - private_outlet
excluded:
  - Pods
line_length:
  error: 120
type_body_length:
  error: 100
file_length:
  error: 200
function_body_length:
  error: 20

reporter: 'xcode'
