platform :ios, '9.0'

target 'cooltizbe' do
  use_frameworks!

  pod 'AppCenter', '1.9.0'
  pod 'RxSwift', '4.3.1'
  pod 'RxCocoa', '4.3.1'
  pod 'SwiftLint', '0.28.2'
  pod 'SkeletonView', '1.4.1'
  pod 'DZNEmptyDataSet', '1.8.1'
  pod 'Alamofire', '4.8.0'

  target 'cooltizbeTests' do
    inherit! :search_paths
  end

  target 'cooltizbeUITests' do
    inherit! :search_paths
  end

end
