# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cooltizbe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cooltizbe
  pod 'AppCenter', '1.9.0'
  pod 'RxSwift', '4.3.1'
  pod 'RxCocoa', '4.3.1'

  target 'cooltizbeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cooltizbeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
